<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns1="http://www.example.org" xmlns:tns="http://xmlns.oracle.com/apps/otm/transmission/v6.4"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://www.getCutomer.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns2="http://www.Sites.org" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns1 ns0 ns2 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/FusionOTMSynchrony/FusionOTMSynchrony/FusionDataCollectionBPELProcess"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FusionDataCollectionBPELProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CustomerResponse" namespace="http://www.getCutomer.org"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FusionDataCollectionBPELProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="AddressResponse" namespace="http://www.example.org"/>
        <oracle-xsl-mapper:param name="getAddress_output"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FusionDataCollectionBPELProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SiteResponse" namespace="http://www.Sites.org"/>
        <oracle-xsl-mapper:param name="getSite_output"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/OTM.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission"
                                       namespace="http://xmlns.oracle.com/apps/otm/transmission/v6.4"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED JAN 29 10:02:01 EET 2025].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="getAddress_output"/>
  <xsl:param name="getSite_output"/>
  <xsl:variable name="SupplierAbbreviation"
                select="xp20:upper-case(substring(translate(normalize-space(/ns0:CustomerResponse/ns0:items/ns0:Supplier), ' ', ''), 1, 22))"/>
  <xsl:template match="/">
    <tns:Transmission>
      <TransmissionHeader>
        <LocationGid>
          <DomainName>
            <xsl:value-of select="$getSite_output/ns2:SiteResponse/ns2:items/ns2:SupplierSite"/>
          </DomainName>
        </LocationGid>
      </TransmissionHeader>
      <TransmissionBody>
        <GLogXMLElement>
          <Location>
            <TransactionCode>
              <xsl:value-of select='"IU"'/>
            </TransactionCode>
            <LocationGid>
              <Gid>
                <DomainName>
                  <xsl:value-of select='"FPL"'/>
                </DomainName>
                <Xid>
                  <xsl:value-of select="$SupplierAbbreviation"/>
                </Xid>
              </Gid>
            </LocationGid>
            <LocationName>
              <xsl:value-of select="/ns0:CustomerResponse/ns0:items/ns0:Supplier"/>
            </LocationName>
            <Description>
              <xsl:value-of select='"CLIENT"'/>
            </Description>
            <Address>
              <AddressLines>
                <SequenceNumber>
                  <xsl:value-of select='"CLIENT"'/>
                </SequenceNumber>
                <AddressLine>
                  <xsl:value-of select="$getAddress_output/ns1:AddressResponse/ns1:items/ns1:AddressLine1"/>
                </AddressLine>
              </AddressLines>
              <City>
                <xsl:value-of select="$getAddress_output/ns1:AddressResponse/ns1:items/ns1:City"/>
              </City>
              <CountryCode3Gid>
                <Gid>
                  <Xid>
                    <xsl:value-of select="$getAddress_output/ns1:AddressResponse/ns1:items/ns1:CountryCode"/>
                  </Xid>
                </Gid>
              </CountryCode3Gid>
              <CountryCode>
                <CountryCode3Gid>
                  <Gid>
                    <Xid>
                      <xsl:value-of select="$getAddress_output/ns1:AddressResponse/ns1:items/ns1:CountryCode"/>
                    </Xid>
                  </Gid>
                </CountryCode3Gid>
                <CountryCode2>
                  <xsl:value-of select="$getAddress_output/ns1:AddressResponse/ns1:items/ns1:CountryCode"/>
                </CountryCode2>
              </CountryCode>
              <TimeZoneGid>
                <Gid>
                  <Xid>
                    <xsl:value-of select='"Asia/Riyadh"'/>
                  </Xid>
                </Gid>
              </TimeZoneGid>
              <Latitude>
                <xsl:value-of select='"24.65"'/>
              </Latitude>
              <Longitude>
                <xsl:value-of select='"46.7"'/>
              </Longitude>
            </Address>
            <LocationRefnum>
              <LocationRefnumQualifierGid>
                <Gid>
                  <DomainName>
                    <xsl:value-of select='"FPL"'/>
                  </DomainName>
                  <Xid>
                    <xsl:value-of select='"CUSTOMER_ACCOUNT_NUM"'/>
                  </Xid>
                </Gid>
              </LocationRefnumQualifierGid>
              <LocationRefnumValue>
                <xsl:value-of select="/ns0:CustomerResponse/ns0:items/ns0:SupplierNumber"/>
              </LocationRefnumValue>
            </LocationRefnum>
            <LocationRefnum>
              <LocationRefnumQualifierGid>
                <Gid>
                  <DomainName>
                    <xsl:value-of select='"FPL"'/>
                  </DomainName>
                  <Xid>
                    <xsl:value-of select='"CUSTOMER_SITE_NUM"'/>
                  </Xid>
                </Gid>
              </LocationRefnumQualifierGid>
              <LocationRefnumValue>
                <xsl:value-of select="$getSite_output/ns2:SiteResponse/ns2:items/ns2:SupplierSite"/>
              </LocationRefnumValue>
            </LocationRefnum>
            <LocationRefnum>
              <LocationRefnumQualifierGid>
                <Gid>
                  <DomainName>
                    <xsl:value-of select='"FPL"'/>
                  </DomainName>
                  <Xid>
                    <xsl:value-of select='"CUST_REGISTRY_ID"'/>
                  </Xid>
                </Gid>
              </LocationRefnumQualifierGid>
              <LocationRefnumValue>
                <xsl:value-of select="/ns0:CustomerResponse/ns0:items/ns0:RegistryId"/>
              </LocationRefnumValue>
            </LocationRefnum>
            <LocationRefnum>
              <LocationRefnumQualifierGid>
                <Gid>
                  <DomainName>
                    <xsl:value-of select='"FPL"'/>
                  </DomainName>
                  <Xid>
                    <xsl:value-of select='"PAYMENT_TERMS"'/>
                  </Xid>
                </Gid>
              </LocationRefnumQualifierGid>
              <LocationRefnumValue>
                <xsl:value-of select='"PAYMENT_TERMS"'/>
              </LocationRefnumValue>
            </LocationRefnum>
            <Contact>
              <ContactGid>
                <Gid>
                  <DomainName>
                    <xsl:value-of select='"FPL"'/>
                  </DomainName>
                  <Xid>
                    <xsl:value-of select="$SupplierAbbreviation"/>
                  </Xid>
                </Gid>
              </ContactGid>
              <TransactionCode>
                <xsl:value-of select='"IU"'/>
              </TransactionCode>
              <CommunicationMethod>
                <ComMethodRank>
                  <xsl:value-of select='"1"'/>
                </ComMethodRank>
                <ComMethodGid>
                  <Gid>
                    <Xid>
                      <xsl:value-of select='"EMAIL"'/>
                    </Xid>
                  </Gid>
                </ComMethodGid>
              </CommunicationMethod>
              <LocationGid>
                <Gid>
                  <DomainName>
                    <xsl:value-of select='"FPL"'/>
                  </DomainName>
                  <Xid>
                    <xsl:value-of select="$SupplierAbbreviation"/>
                  </Xid>
                </Gid>
              </LocationGid>
            </Contact>
            <LocationRole>
              <LocationRoleGid>
                <Gid>
                  <DomainName>
                    <xsl:value-of select='"FPL"'/>
                  </DomainName>
                  <Xid>
                    <xsl:value-of select='"CLIENT"'/>
                  </Xid>
                </Gid>
              </LocationRoleGid>
            </LocationRole>
            <Corporation>
              <CorporationGid>
                <Gid>
                  <DomainName>
                    <xsl:value-of select='"FPL"'/>
                  </DomainName>
                  <Xid>
                    <xsl:value-of select="$SupplierAbbreviation"/>
                  </Xid>
                </Gid>
              </CorporationGid>
              <TransactionCode>
                <xsl:value-of select='"IU"'/>
              </TransactionCode>
              <CorporationName>
                <xsl:value-of select="/ns0:CustomerResponse/ns0:items/ns0:Supplier"/>
              </CorporationName>
            </Corporation>
            <PrimaryAddressLineSeq>
              <xsl:value-of select='"1"'/>
            </PrimaryAddressLineSeq>
            <IsActive>
              <xsl:value-of select='"Y"'/>
            </IsActive>
          </Location>
        </GLogXMLElement>
      </TransmissionBody>
    </tns:Transmission>
  </xsl:template>
</xsl:stylesheet>
